<?php
$files = [
    'OrderCreatedNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass OrderCreatedNotification extends Notification {\n    use Queueable;\n    public \$order;\n    public function __construct(\$order) { \$this->order = \$order; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'pesanan_baru',\n            'title' => 'Pesanan Baru #' . \$this->order->id,\n            'message' => 'Pesanan baru senilai Rp' . number_format(\$this->order->total_price ?? 0, 0, ',', '.'),\n            'url' => route('admin.orders.show', \$this->order->id),\n            'icon' => 'fas fa-shopping-cart text-primary'\n        ];\n    }\n}",
    'StockLowNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass StockLowNotification extends Notification {\n    use Queueable;\n    public \$product;\n    public \$count;\n    public function __construct(\$product, \$count) { \$this->product = \$product; \$this->count = \$count; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'stok_menipis',\n            'title' => 'Stok Menipis',\n            'message' => 'Stok \"' . \$this->product->name . '\" tersisa ' . \$this->count . '!',\n            'url' => route('admin.products.index'),\n            'icon' => 'fas fa-exclamation-triangle text-warning'\n        ];\n    }\n}",
    'StockAddedNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass StockAddedNotification extends Notification {\n    use Queueable;\n    public \$product;\n    public \$count;\n    public function __construct(\$product, \$count) { \$this->product = \$product; \$this->count = \$count; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'stok_ditambah',\n            'title' => 'Stok Ditambah',\n            'message' => \$this->count . ' stok ditambahkan untuk \"' . \$this->product->name . '\"',\n            'url' => route('admin.products.index'),\n            'icon' => 'fas fa-box-open text-success'\n        ];\n    }\n}",
    'NewChatMessageNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass NewChatMessageNotification extends Notification {\n    use Queueable;\n    public \$messageText;\n    public \$senderName;\n    public function __construct(\$messageText, \$senderName) { \$this->messageText = \$messageText; \$this->senderName = \$senderName; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'pesan_baru',\n            'title' => 'Pesan Baru',\n            'message' => 'Dari ' . \$this->senderName . ': ' . Str::limit(\$this->messageText, 30),\n            'url' => url('/admin/chats'),\n            'icon' => 'fas fa-envelope text-info'\n        ];\n    }\n}",
    'PayoutRequestNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass PayoutRequestNotification extends Notification {\n    use Queueable;\n    public \$sellerName;\n    public function __construct(\$sellerName) { \$this->sellerName = \$sellerName; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'permintaan_payout',\n            'title' => 'Permintaan Payout',\n            'message' => 'Seller ' . \$this->sellerName . ' meminta penarikan dana.',\n            'url' => url('/admin/withdrawals'),\n            'icon' => 'fas fa-money-bill-wave text-success'\n        ];\n    }\n}",
    'SystemEventNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass SystemEventNotification extends Notification {\n    use Queueable;\n    public \$eventTitle;\n    public \$eventMessage;\n    public function __construct(\$eventTitle, \$eventMessage) { \$this->eventTitle = \$eventTitle; \$this->eventMessage = \$eventMessage; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'system_event',\n            'title' => \$this->eventTitle,\n            'message' => \$this->eventMessage,\n            'url' => '#',\n            'icon' => 'fas fa-cogs text-secondary'\n        ];\n    }\n}",
    'FailedLoginNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass FailedLoginNotification extends Notification {\n    use Queueable;\n    public \$ipAddress;\n    public function __construct(\$ipAddress) { \$this->ipAddress = \$ipAddress; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'login_gagal',\n            'title' => 'Percobaan Login Gagal',\n            'message' => 'Ada percobaan login gagal dari IP: ' . \$this->ipAddress,\n            'url' => '#',\n            'icon' => 'fas fa-shield-alt text-danger'\n        ];\n    }\n}",
    'OrderStatusNotification' => "<?php\nnamespace App\Notifications;\nuse Illuminate\Bus\Queueable;\nuse Illuminate\Notifications\Notification;\nclass OrderStatusNotification extends Notification {\n    use Queueable;\n    public \$orderId;\n    public \$statusMessage;\n    public function __construct(\$orderId, \$statusMessage) { \$this->orderId = \$orderId; \$this->statusMessage = \$statusMessage; }\n    public function via(\$notifiable) { return ['database']; }\n    public function toArray(\$notifiable) {\n        return [\n            'type' => 'status_pesanan',\n            'title' => 'Pembaruan Pesanan #' . \$this->orderId,\n            'message' => \$this->statusMessage,\n            'url' => url('/orders/' . \$this->orderId),\n            'icon' => 'fas fa-info-circle text-primary'\n        ];\n    }\n}",
];

foreach ($files as $name => $content) {
    file_put_contents(__DIR__ . '/app/Notifications/' . $name . '.php', $content);
}
echo "Classes overwritten.\n";
